version: '{build}'
os: Visual Studio 2015 CTP 6
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: HWkLYKGSAMll1EHxm0ggW6nikT9BOHReONIbOmLhCCX8+o8DFfabZXyr5MneaXyS
install:
- ps: >-
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.ps1'))

    $env:Path = "C:\Program Files (x86)\MSBuild\14.0\Bin;" + [Environment]::GetEnvironmentVariables("Machine")["Path"] + ";" + [Environment]::GetEnvironmentVariables("User")["Path"]

    kvm upgrade
before_build:
- ps: kpm restore
build:
  project: NETCore/Nito.CalculatedProperties.sln  verbosity: minimal
test_script:
- ps: >-
    cd NETCore

    ./Coverage.ps1